### ISSUE TITLE
TT04 cutscene not removed

### ISSUE THREAD

**Issue by Xeeynamo** [thundrio-kh/kh2-cutscene-remover#1]
I noticed that this cutscene is still played. The map is TT04:
![image](https://user-images.githubusercontent.com/6128729/110297481-6f859680-7feb-11eb-9c69-5b0099954661.png)

**Comment by snelson3** [comment]
I left this cutscene in at first because when removing it you were unable to choose your weapon. However I made an improvement which allows this cutscene to be removed, while still letting you choose your weapon (as the cutscene that needs to be there is just the popup saying you got a stat boost).

Also updating the mod.yml to mention the cutscenes that cannot be removed due to softlocks
